apiVersion: v1
kind: Service
metadata:
  name: finlex-typesense-svc
spec:
  selector:
    app: finlex-typesense
  ports:
    - protocol: TCP
      port: 8000         
      targetPort: 3001
  type: ClusterIP
