apiVersion: v1
kind: ConfigMap
metadata:
  name: finlex-lukija-config
data:
  PG_URI: postgres://finlex_lukija_db:E2cETBXeCtGsdRaRO4nR@possu-test.it.helsinki.fi:5432/finlex_lukija_db?targetServerType=primary&ssl=true
  DATABASE_PASSWORD: kettu
  TYPESENSE_API_KEY: seppo

