kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: finlex-lukija
  labels:
    app: finlex-lukija
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: arttkan/finlex-lukija:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local