name: Build and push docker image (production)

on:
  release:
    types: [published]

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build frontend
        run: |
          npm --prefix ./frontend ci
          npm --prefix ./frontend run build
      - name: Build backend
        run: |
          npm --prefix ./backend ci
          npm --prefix ./backend run build
      - name: Build and and export
        uses: redhat-actions/push-to-registry@v2
        with:
          context: .
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}
   
