name: Build and push docker image (production)

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: docker.io/<dockerhub-käyttäjänimi>/finlex
          tags: production,${{ github.sha }}
          containerfiles: ./Dockerfile
          build-args: |
            GIT_SHA=${{ github.sha }}
            STAGING=false         
    
      - name: Push image to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
