name: Test e2e
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test_e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Build frontend
        run: |
          npm --prefix ./frontend ci
          npm --prefix ./frontend run build
      - name: Build backend and get browser
        run: |
          cd backend
          npx playwright install --with-deps
          npm ci
          npm run build
          npm start > backend_prod.log 2>&1 &
          sleep 5
          for i in {1..30}; do
            if curl --fail http://localhost:3001 > /dev/null 2>&1; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting for backend..."
            sleep 1
          done
          npx playwright test