name: Test e2e
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run E2E Tests
        run: docker compose -f run_e2e.yaml up --build --exit-code-from playwright
      