name: Test frontend
on:
  push:
    branches:
      - frontend
    paths:
      - 'frontend/**'

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Run build
        run: npm build
