name: Test e2e
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test_e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PG_URI: postgres://postgres:postgres@postgres:5432/testdb
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Install and build
        run: |
          npm --prefix ./frontend ci
          npm --prefix ./frontend run build
          npm --prefix ./backend ci
          npm --prefix ./backend run build
      - name: Start backend
        working-directory: ./backend
        run: |
          npm run test:bg
          sleep 5
      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:3001 > /dev/null 2>&1; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting for backend..."
            sleep 1
          done
      - name: Run Playwright tests
        working-directory: ./backend
        run: |
          npx playwright test