name: Test e2e
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Dependencies
        run: npm ci
      - name: playwright browser
        run: npx playwright install --with-deps

      - name: Build frontend
        run: |
          npm --prefix ./frontend install
          npm --prefix ./frontend run build
      - name: Build backend
        run: |
          npm --prefix ./backend ci
          npm --prefix ./backend start > backend_prod.log 2>&1 &

      - name: Run tests
        run: npx playwright test