name: Test e2e
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test_e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Build backend
        run: |
          npm --prefix ./frontend ci
          npm --prefix ./frontend run build
          npm --prefix ./backend ci
          npm --prefix ./backend run build
          npm --prefix ./backend start > backend_prod.log 2>&1 &
          cd backend
          npx playwright install --with-deps
          npx playwright test
